### ISSUE TITLE
Compile error after 1.2.5

### ISSUE THREAD

**Issue by gauravmc** [zoom/sample-app-videosdk#18]
Looks like the third param in `VideoClient`'s `init` method was updated to be [type `InitOptions` instead of `string`](https://github.com/zoom/videosdk-web/pull/15/files#diff-6c72c406899fba6c8b5dc9c1bbd258195d0968cf383597865448c9e5616c8b1cR164), but corresponding change wasn't made in the [sample app](https://github.com/zoom/sample-app-videosdk/blob/8ac324807795684cd414bfeebd072848e3a3a227/react-demo/src/App.tsx#L107). So trying to run it after a fresh install results in this error (causing it to not compile):

```
Failed to compile.

/Users/abc/Code/xyz/sample-app-videosdk/react-demo/src/App.tsx
TypeScript error in /Users/abc/Code/xyz/sample-app-videosdk/react-demo/src/App.tsx(107,69):
Argument of type '"zoom.us"' is not assignable to parameter of type 'InitOptions | undefined'.
```

cc @mayk-zoom

**Comment by mayk-zoom** [comment]
Hi there, thanks for reporting the issue. We'll take a look and update with a fix as soon as we can

**Comment by mayk-zoom** [comment]
This has been fixed with the following commit: 
https://github.com/zoom/sample-app-videosdk/commit/17df81dc001865018704ef05d5b3973ae6c47c66

Will be closing the issue. Thanks again for highlighting it!
